formdata:
  student_id: 1190113189
  state: 1
  is_body_ok: 1
  is_gl: 0
  is_tl: 0
  is_jc: 0
  is_2_man: 0
  is_family: 0
  user_location: 1
  location_province: 贵州省
  location_city: 铜仁市
  location_country: 印江土家族苗族自治县
  morning_state: 1
  morning_temperature:
  afternoon_state: 1
  afternoon_temperature:
  is_jkm: 1
  longitude: 108:40611
  latitude: 27:998192
  uid: 1190113189
  session: ak5POU5mRXRoRktMYjhRUzUyMzV2VjdCMmZpV2dRS0k4S0szZDd1MWtSWlZQTm9FemlpYldua2hPNkh0cGdKTkRteEI3bUROKzlBPQ==

